export const SEARCH_TWEETS = 'SEARCH_TWEETS';
export const SEARCH_TWEETS_SUCCESS = 'SEARCH_TWEETS_SUCCESS';
export const SET_ERROR_INFO= 'SET_ERROR_INFO';
export const RESET_STORE_DATA = 'RESET_STORE_DATA';